skip_tags: true # avoid deploy to GitHub loop 

image: Visual Studio 2017

configuration:
#- Debug
- Release

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
- ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
- nuget restore -Verbosity quiet
  #- ps: Vsix-TokenReplacement src\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'


build:
  verbosity: minimal              # MSBuild verbosity level


after_test:
- ps: Vsix-PushArtifacts | Vsix-PublishToGallery
